{{- if and (.Values.ingress.enabled) (.Values.ingress.tls) -}}
{{- $fullName := include "filebrowser.fullname" . -}}
{{- $labels := include "filebrowser.labels" . -}}
{{- range .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    {{- $labels }}
type: kubernetes.io/tls
data:
  tls.crt: {{ ($.Files.Get "files/filebrowser.crt" | b64enc) | quote }}
  tls.key: {{ ($.Files.Get "files/filebrowser.key" | b64enc) | quote }}
{{- end }}
{{- end }}
